CREATE TABLE tb1_board (
	bno INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(200) NOT NULL,
	content VARCHAR(20000) NOT NULL,
	writer VARCHAR(5) NOT NULL,
	regdate DATETIME DEFAULT NOW(),
	updatedate DATETIME DEFAULT NOW()
);